// Code generated by tools/gen_realtime_proto.mjs. DO NOT EDIT.
// Source: shared/proto/realtime.json

import type { Position, WorldPlayer, CharacterAppearance, CharacterEquipment, TileUpdate } from "./protocol";

export type WSClientMessage =
  | {
      type: "auth";
      token: string;
    }
  | {
      type: "move";
      position: Position;
    }
  | {
      type: "ping";
    };

export type WSServerMessage =
  | {
      type: "auth_ok";
      playerId: string;
      characterId: string;
      characterName: string;
      worldId: string;
      mapId: string;
      position: Position;
      players: WorldPlayer[];
    }
  | {
      type: "player_joined";
      playerId: string;
      characterId: string;
      characterName: string;
      mapId: string;
      position: Position;
      appearance: CharacterAppearance;
      equipment: CharacterEquipment;
    }
  | {
      type: "player_moved";
      playerId: string;
      mapId: string;
      position: Position;
    }
  | {
      type: "player_left";
      playerId: string;
    }
  | {
      type: "move_ack";
      mapId: string;
      position: Position;
      transitioned: boolean;
    }
  | {
      type: "pong";
    }
  | {
      type: "tile_update";
      tile: TileUpdate;
    }
  | {
      type: "error";
      error: string;
    };

export const WS_CLIENT_TYPES = ["auth","move","ping"] as const;
export const WS_SERVER_TYPES = ["auth_ok","player_joined","player_moved","player_left","move_ack","pong","tile_update","error"] as const;

