// Code generated by tools/gen_realtime_proto.mjs. DO NOT EDIT.
// Source: shared/proto/realtime.json

package protocol

// Realtime WebSocket message type tokens.
const (
	MsgClientAuth = "auth"
	MsgClientMove = "move"
	MsgClientPing = "ping"
	MsgServerAuthOk = "auth_ok"
	MsgServerPlayerJoined = "player_joined"
	MsgServerPlayerMoved = "player_moved"
	MsgServerPlayerLeft = "player_left"
	MsgServerMoveAck = "move_ack"
	MsgServerPong = "pong"
	MsgServerTileUpdate = "tile_update"
	MsgServerError = "error"
)

