#!/usr/bin/env node
// 从 shared/proto/realtime.json 生成实时层协议的 Go 常量与 TypeScript 类型。
// 用法: node tools/gen_realtime_proto.mjs
// 说明: 只生成实时 WS 层（消息类型串、信封字段），大体量的 Character/Appearance 结构仍由手写文件提供并被引用。

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const spec = JSON.parse(readFileSync(join(root, "shared/proto/realtime.json"), "utf8"));

// 字段类型 -> Go / TS 映射。复合类型引用手写协议里已有的结构。
const goType = {
  string: "string",
  bool: "bool",
  Position: "Position",
  "WorldPlayer[]": "[]WorldPlayer",
  CharacterAppearance: "CharacterAppearance",
  CharacterEquipment: "CharacterEquipment",
  TileUpdate: "TileUpdate",
};
const tsType = {
  string: "string",
  bool: "boolean",
  Position: "Position",
  "WorldPlayer[]": "WorldPlayer[]",
  CharacterAppearance: "CharacterAppearance",
  CharacterEquipment: "CharacterEquipment",
  TileUpdate: "TileUpdate",
};

const clientTypes = Object.keys(spec.clientMessages);
const serverTypes = Object.keys(spec.serverMessages);

function goConstName(prefix, t) {
  const camel = t.split("_").map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("");
  return `Msg${prefix}${camel}`;
}

// ---------- Go ----------
const goLines = [];
goLines.push("// Code generated by tools/gen_realtime_proto.mjs. DO NOT EDIT.");
goLines.push("// Source: shared/proto/realtime.json");
goLines.push("");
goLines.push("package protocol");
goLines.push("");
goLines.push("// Realtime WebSocket message type tokens.");
goLines.push("const (");
for (const t of clientTypes) goLines.push(`\t${goConstName("Client", t)} = ${JSON.stringify(t)}`);
for (const t of serverTypes) goLines.push(`\t${goConstName("Server", t)} = ${JSON.stringify(t)}`);
goLines.push(")");
goLines.push("");
writeFileSync(join(root, "server/internal/protocol/realtime_gen.go"), goLines.join("\n") + "\n");

// ---------- TypeScript ----------
const tsLines = [];
tsLines.push("// Code generated by tools/gen_realtime_proto.mjs. DO NOT EDIT.");
tsLines.push("// Source: shared/proto/realtime.json");
tsLines.push("");
tsLines.push('import type { Position, WorldPlayer, CharacterAppearance, CharacterEquipment, TileUpdate } from "./protocol";');
tsLines.push("");

function tsFields(fields, indent) {
  const out = [];
  for (const [name, type] of Object.entries(fields)) {
    const mapped = tsType[type];
    if (!mapped) throw new Error(`未知字段类型: ${type}`);
    out.push(`${indent}${name}: ${mapped};`);
  }
  return out;
}

// 客户端 -> 服务端消息联合类型
tsLines.push("export type WSClientMessage =");
const clientVariants = clientTypes.map((t) => {
  const fields = spec.clientMessages[t].fields;
  const body = tsFields(fields, "      ");
  const lines = [`  | {`, `      type: ${JSON.stringify(t)};`, ...body, `    }`];
  return lines.join("\n");
});
tsLines.push(clientVariants.join("\n") + ";");
tsLines.push("");

// 服务端 -> 客户端消息联合类型
tsLines.push("export type WSServerMessage =");
const serverVariants = serverTypes.map((t) => {
  const fields = spec.serverMessages[t].fields;
  const body = tsFields(fields, "      ");
  const lines = [`  | {`, `      type: ${JSON.stringify(t)};`, ...body, `    }`];
  return lines.join("\n");
});
tsLines.push(serverVariants.join("\n") + ";");
tsLines.push("");

tsLines.push("export const WS_CLIENT_TYPES = " + JSON.stringify(clientTypes) + " as const;");
tsLines.push("export const WS_SERVER_TYPES = " + JSON.stringify(serverTypes) + " as const;");
tsLines.push("");

writeFileSync(join(root, "client/web/src/protocol.gen.ts"), tsLines.join("\n") + "\n");

console.log("generated:");
console.log("  server/internal/protocol/realtime_gen.go");
console.log("  client/web/src/protocol.gen.ts");
